In [1]:
import numpy as np

In [2]:
ar1=np.array([1,2,3])
ar1.reshape(1,3)
ar1.shape


(3,)

In [3]:
ar2=np.array([3,6,9])
ar2

array([3, 6, 9])

In [4]:
np.dot(ar1,ar2)

42

In [5]:
A=np.array([[1,2,3],[3,6,9]])
A.shape

(2, 3)

</h4> Note what's happening in the cell below. I have added it after our session.

In [6]:
np.dot(A,ar2)
#Figure out the details of this. prractice by changing values to make sure you know how it's working.

array([ 42, 126])

In [7]:
A

array([[1, 2, 3],
       [3, 6, 9]])

In [8]:
B=np.array([1,2,3]) 
B.shape

(3,)

In [9]:
A/B  #elementwise division Numpy creates a second copy of B and stacks it over B and then does elementwise division

array([[1., 1., 1.],
       [3., 3., 3.]])

In [10]:
 print(A/B)

[[1. 1. 1.]
 [3. 3. 3.]]


In [11]:
C=A*B
C.shape


(2, 3)

In [12]:
A/B

array([[1., 1., 1.],
       [3., 3., 3.]])

In [13]:
C=np.array([1,0])
C

array([1, 0])

In [14]:
x=np.array([1,2,4])
x_norm = np.linalg.norm(x,axis=0,keepdims=True)
x_norm


array([4.58257569])

In [15]:
def norm(x):
    return np.linalg.norm(x,axis=1,keepdims=True)

def Sigmoid (x):
    return x+1

Sigmoid(C)


array([2, 1])

In [16]:
norm(A*B)

array([[ 9.89949494],
       [29.69848481]])

In [17]:
x=np.array([[3,4,5],[0,9,3]])
#x
np.sum(x[0]+x[1])

24

In [18]:
x=np.array([[1,2],[3,4]])


In [19]:
a3darray = np.zeros((2, 2, 2))
a3darray


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
a3darray[1][1][1]=5
a3darray[1][1][0]=9
a3darray[0][0][1]=5

In [21]:
a3darray


array([[[0., 5.],
        [0., 0.]],

       [[0., 0.],
        [9., 5.]]])

In [22]:
D=np.array([[1],[2],[3]])
D
D.shape

(3, 1)

In [23]:
np.log(5)  

np.log(A)

array([[0.        , 0.69314718, 1.09861229],
       [1.09861229, 1.79175947, 2.19722458]])